#include <stdio.h>
// About functions types
void display();// This is called a Function prototype/function prototype/function prototype
int main () {
	
    int a = 20;
    int b = 10;
    
    printf(" value of a+b is %d \n",a+b);
    display(); // This step is called fucntion call / function call/ functio call/
    display();
    display();
    display();
    printf(" value of a-b is %d  \n",a-b);
	
	return 0;
}
void display(){ // This is called a function definintionn //  Funbction definition  
// Function definitio// function definition// function definition// function definiton
	printf("My name is yubraj pariyar\n");
	//printf(" i recently live in baneshwor area kathmandu\n");
	//printf(" am come from pokhara\n");
	//printf(" Father name dal nahadur pariyar\n");
	//printf("  my mother name is mina pariyar\n");
}
